# Generated by Django 5.1.5 on 2025-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('DIRECTOR', 'Директор'), ('HR', 'HR'), ('RECRUITER', 'Рекрутер'), ('PRACTICE_SUPERVISOR', 'Руководитель практики')], default='STUDENT', max_length=20),
        ),
    ]
