# Generated by Django 5.1.5 on 2025-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('DIRECTOR', 'Директор'), ('HR', 'HR'), ('RECRUITER', 'Рекрутер'), ('PRACTICE_SUPERVISOR', 'Руководитель практики')], default='STUDENT', max_length=50),
        ),
    ]
