# Generated by Django 5.1.5 on 2025-01-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание вакансии")),
                (
                    "requirements",
                    models.TextField(verbose_name="Требования к кандидатам"),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок подачи заявок"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая вакансия"),
                            ("STUDENT_APPLIED", "Заявка студента создана"),
                            ("UNDER_REVIEW", "Заявка на рассмотрении подразделения"),
                            ("INTERVIEW_SCHEDULED", "Ожидает собеседования"),
                            ("INTERVIEW_STAGE", "На стадии собеседования"),
                            ("CLOSED", "Вакансия закрыта"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус вакансии",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активна ли вакансия"
                    ),
                ),
                (
                    "hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="HR, создавший вакансию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(verbose_name="Сопроводительное сообщение"),
                ),
                (
                    "resume",
                    models.FileField(upload_to="resumes/", verbose_name="Резюме"),
                ),
                (
                    "preferred_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Предпочтительная дата начала работы",
                    ),
                ),
                (
                    "interview_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время собеседования"
                    ),
                ),
                (
                    "interview_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место проведения собеседования",
                    ),
                ),
                (
                    "interview_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка для онлайн-встречи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая вакансия"),
                            ("STUDENT_APPLIED", "Заявка студента создана"),
                            ("UNDER_REVIEW", "Заявка на рассмотрении подразделения"),
                            ("INTERVIEW_SCHEDULED", "Ожидает собеседования"),
                            ("INTERVIEW_STAGE", "На стадии собеседования"),
                            ("CLOSED", "Вакансия закрыта"),
                        ],
                        default="STUDENT_APPLIED",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="vacancies.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вакансию",
                "verbose_name_plural": "Заявки на вакансии",
            },
        ),
    ]
